import { marked } from "marked";
import { Badge } from "@/components/ui/badge";
import { Sparkles } from "lucide-react";
import type { SkillEnrichment } from "@/lib/skill-enrichment";
import { componentRows } from "@/lib/skill-enrichment";
import { ComponentsToggle } from "@/components/skill-enrichment-components-toggle";

type Props = {
  enrichment: SkillEnrichment;
  author?: string | null;
  source: string;
};

// Strip leading YAML frontmatter for display. Kept in raw content for copy
// + export, but it clutters the rendered detail page.
function stripFrontmatter(md: string): string {
  let body = md.trimStart();
  if (body.startsWith("---")) {
    const closingIdx = body.indexOf("\n---", 3);
    if (closingIdx !== -1) body = body.slice(closingIdx + 4).trimStart();
  }
  return body;
}

// Server component. Renders the enriched markdown to HTML at request time,
// caches at the edge per the page's revalidate window.
export async function SkillEnrichmentPanel({
  enrichment,
  author,
  source,
}: Props) {
  const enrichedContent = enrichment.enriched_content ?? "";
  const summary = enrichment.enrichment_summary;
  const rows = componentRows(enrichment.components_present);

  const body = stripFrontmatter(enrichedContent);
  const html = await marked.parse(body, {
    async: true,
    gfm: true,
    breaks: false,
  });

  const enrichedDate = enrichment.enriched_at
    ? new Date(enrichment.enriched_at).toISOString().slice(0, 10)
    : null;

  return (
    <section className="mb-10" id="canonical-skill">
      <div className="flex flex-wrap items-center justify-between gap-3 mb-4">
        <div className="flex items-center gap-2 flex-wrap">
          <Badge
            variant="outline"
            className="bg-emerald-950/40 text-emerald-300 border-emerald-900 inline-flex items-center gap-1.5 text-[11px] uppercase tracking-wider"
          >
            <Sparkles className="size-3" aria-hidden="true" />
            implexa-enriched
          </Badge>
          <span className="text-[11px] text-zinc-600">
            canonical version
            {enrichedDate ? ` · ${enrichedDate}` : ""}
            {enrichment.enriched_by_model
              ? ` · ${enrichment.enriched_by_model}`
              : ""}
          </span>
        </div>
        {rows.length > 0 ? <ComponentsToggle rows={rows} /> : null}
      </div>

      {summary ? (
        <p className="text-sm text-zinc-400 italic mb-5 leading-relaxed">
          {summary}
        </p>
      ) : null}

      <div
        className="prose prose-invert prose-zinc max-w-none
          prose-headings:tracking-tight
          prose-h1:text-2xl prose-h1:font-semibold prose-h1:mb-4 prose-h1:mt-0 prose-h1:text-white
          prose-h2:text-xl prose-h2:font-semibold prose-h2:mt-8 prose-h2:mb-3 prose-h2:text-white
          prose-h3:text-base prose-h3:font-semibold prose-h3:mt-6 prose-h3:mb-2 prose-h3:text-white
          prose-p:text-zinc-300 prose-p:leading-relaxed
          prose-a:text-white prose-a:underline prose-a:decoration-zinc-600 hover:prose-a:decoration-white
          prose-strong:text-white
          prose-code:text-zinc-200 prose-code:bg-zinc-900 prose-code:px-1.5 prose-code:py-0.5 prose-code:rounded prose-code:text-[0.875em] prose-code:before:content-none prose-code:after:content-none
          prose-pre:bg-zinc-950 prose-pre:border prose-pre:border-zinc-900 prose-pre:text-zinc-200 prose-pre:rounded-lg prose-pre:text-sm
          prose-li:text-zinc-300
          prose-ul:my-3 prose-ol:my-3
          prose-hr:border-zinc-900 prose-hr:my-8
          prose-blockquote:border-zinc-800 prose-blockquote:text-zinc-400"
        // Enriched content is generated by Implexa via Haiku with a strict
        // voice prompt + em-dash scrub on the backend. Marked sanitizes
        // by default; we trust the pipeline.
        dangerouslySetInnerHTML={{ __html: html }}
      />

      <div className="mt-6 pt-4 border-t border-zinc-900 text-xs text-zinc-500">
        {author ? (
          <>
            by <span className="text-zinc-300">@{author}</span> (source:{" "}
            <span className="text-zinc-300">{source}</span>), enriched by{" "}
            <span className="text-zinc-300">implexa</span>
          </>
        ) : (
          <>
            source: <span className="text-zinc-300">{source}</span>, enriched
            by <span className="text-zinc-300">implexa</span>
          </>
        )}
      </div>
    </section>
  );
}
